<!-- Manual de PHP --> 

<?php 
function CabeceraPagina() 
{ 
?> 
    <font size="+1">Esta cabecera estará en todas sus páginas.</font><br> 
    <hr> 
<?php 
} 

function PiePagina() 
{ 
?> 
    <hr> 
    <font size="-1">Este es el pie de página.</font><br> 
    Autor: John Doe 
<?php 
} 

function Indice() 
{ 
?> 
    <a href="ejem06a.phtml">Página 1</a><br> 
    <a href="ejem06a2.phtml">Página 2</a><br> 
<?php 
} 
?>
